font_family Ubuntu Mono Nerd Font
bold_font Ubuntu Mono Bold Nerd Font Complete
italic_font Ubuntu Mono Italic Nerd Font Complete
bold_italic_font Ubuntu Mono Bold Italic Nerd Font Complete
font_size 16

adjust_line_height 5 
adjust_column_width 0

window_padding_width  1 10
